### PR TITLE
Add a Nix flake

### PR DESCRIPTION
**Pull request by magistau**

### CODE REVIEW

**Comment by magistau** [comment]
@kamillaova mind reviewing?

**Review by portasynthinca3 — COMMENTED** [review]
What's the purpose of `nix/dummy.rs`?

**Comment by magistau** [comment]
> What's the purpose of `nix/dummy.rs`?

It is needed to build dependencies as a separate derivation, s.t. they can be cached and reused as long as `Cargo.lock` and `.cargo/config.toml` are not modified. `crane` has a default way of creating a "dummy src", but that is not enough in this case, since it needs an `efi_main` or something like that. See [`mkDummySrc`](https://crane.dev/API.html#cranelibmkdummysrc) and the issue linked in `flake.nix` at the `dummy.rs` use for more insight.

**Comment by portasynthinca3** [comment]
Looks good to me even though I don't know Nix at all :)

**Comment by portasynthinca3** [comment]
It appears that Kamilla does not want to review the pull request, which is totally fine. Merging now, thank you for your contribution.

**Pull request merged**
